name: SimpleBackpacks
version: '${project.version}'
main: de.silentesc.simplebackpacks.Main
api-version: '1.20'
authors: [silentesc]
description: A simple Spigot 1.20.2 plugin for backpacks you can craft in your crafting table
